--- 
abstract: TFIDF Calculator based on MeCab.
author: 
  - Takeshi Miki <miki@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Lingua-JA-TFIDF
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  HTML::Feature: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
  Storable: 0
  XML::TreePP: 0
version: 0.00001
